### ISSUE TITLE
couriersrs-0.1.2-automake-fixes.diff

### ISSUE THREAD

**Issue by szepeviktor** [navsystem/gentoo-portage#1]
https://github.com/navsystem/gentoo-portage/blob/5780f8a4ccff8b94adfbb80da0678346aa1d1365/mail-filter/couriersrs/files/couriersrs-0.1.2-automake-fixes.diff

Good morning!
Is `mkinstalldirs = @mkdir_p@` gentoo-specific or something else?
I have the same problem here https://github.com/szepeviktor/couriersrs/commit/f06f7097510847c3c5d88a10a938e61636cac9ee

Thank you.

**Comment by szepeviktor** [comment]
Could it be a Makefile thing?
https://github.com/szepeviktor/couriersrs/blob/master/Makefile.in#L251

**Comment by eegorov** [comment]
I think you should ask the maintainer in this package. His contact details are listed here:
https://github.com/navsystem/gentoo-portage/blob/5780f8a4ccff8b94adfbb80da0678346aa1d1365/mail-filter/couriersrs/metadata.xml
